# Generated by Django 5.0.6 on 2024-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_name_userprofile_patronymic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('inject', 'Инъекционная косметология'), ('aesthetic', 'Эстетическая косметология')], max_length=50, null=True, verbose_name='Тип косметологии')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название события')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TextField(blank=True, null=True, verbose_name='Время проведения')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
