# Generated by Django 5.0.6 on 2024-06-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_record_delete_consult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.TextField(blank=True, null=True, verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('inject', 'Инъекционная косметология'), ('aesthetic', 'Эстетическая косметология')], default='inject', max_length=50, verbose_name='Тип косметологии'),
        ),
        migrations.CreateModel(
            name='ProcedureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип косметологии')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Отменена')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись на процедуру',
                'verbose_name_plural': 'Записи на процедуры',
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
