# Generated by Django 5.0.6 on 2024-06-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_service_annotation_alter_service_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurerecord',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='procedurerecord',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_responses', to='main.userprofile', verbose_name='Профиль клиента'),
        ),
    ]
