# Generated by Django 5.0.6 on 2024-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_procedurerecord_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurerecord',
            name='response',
            field=models.BooleanField(default=False, verbose_name='Отклик на сободную запись'),
        ),
    ]
