# Generated by Django 5.0.6 on 2024-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_procedurerecord_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Текст записи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Изображение')),
                ('author', models.TextField(blank=True, null=True, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Запись в блоге',
                'verbose_name_plural': 'Записи в блоге',
            },
        ),
    ]
