# Generated by Django 5.0.6 on 2024-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='deadline',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
    ]
